# -*- coding: utf-8 -*-
"""
sic_data.py — SIC code data for Companies House Prospector
Imported by both streamlit_app.py and worker.py.
"""

# ─── Priority industries (Dave's curated shortlist — shown first in UI) ───────
SIC_OPTIONS = [
    ("Accounting / bookkeeping (69201)", "69201"),
    ("Advertising agencies (73110)", "73110"),
    ("Antiques (47791)", "47791"),
    ("Architectural activities (71111)", "71111"),
    ("Architecture (71112)", "71112"),
    ("Art galleries retail (47781)", "47781"),
    ("Auditing (69202)", "69202"),
    ("Barristers (69101)", "69101"),
    ("Building construction (41202)", "41202"),
    ("Business support services (82190)", "82190"),
    ("Car dealerships (45111)", "45111"),
    ("Care agencies / staffing (78300)", "78300"),
    ("Carpentry / joinery (43320)", "43320"),
    ("Catering / event catering (56210)", "56210"),
    ("Cosmetic / plastic surgery clinics (86102)", "86102"),
    ("Craft brewing (11050)", "11050"),
    ("Dental practices (86220)", "86220"),
    ("Distilling / spirits (11010)", "11010"),
    ("Electrical installation (43210)", "43210"),
    ("Engineering consultancy (71121)", "71121"),
    ("Estate agents (68310)", "68310"),
    ("Event management - conferences (82302)", "82302"),
    ("Event management - exhibitions (82301)", "82301"),
    ("General building contractors (41201)", "41201"),
    ("GP practices (86210)", "86210"),
    ("Graphic design (74101)", "74101"),
    ("HR consulting (70229)", "70229"),
    ("Immigration consultants (69109)", "69109"),
    ("Insurance brokers (66220)", "66220"),
    ("IT consultancy (62020)", "62020"),
    ("IT support / infrastructure (62090)", "62090"),
    ("Landscaping (81300)", "81300"),
    ("Management consulting (70229)", "70229"),
    ("Market research (73200)", "73200"),
    ("Mortgage brokers (66190)", "66190"),
    ("Opticians (86230)", "86230"),
    ("Osteopathy / chiropractic (86901)", "86901"),
    ("Painting / decorating (43341)", "43341"),
    ("Physical wellbeing / spa (96040)", "96040"),
    ("Physiotherapy (86901)", "86901"),
    ("Plumbing / heating (43220)", "43220"),
    ("PR / communications (70210)", "70210"),
    ("Property buying & selling (68100)", "68100"),
    ("Property development (41100)", "41100"),
    ("Property management (68320)", "68320"),
    ("Quantity surveying (74902)", "74902"),
    ("Racehorse owners (93191)", "93191"),
    ("Recruitment (78200)", "78200"),
    ("Software development (62012)", "62012"),
    ("Solicitors (69102)", "69102"),
    ("Sound recording / music publishing (59200)", "59200"),
    ("Specialist construction (43990)", "43990"),
    ("Surveying (71112)", "71112"),
    ("Tax consulting (69203)", "69203"),
    ("Tour operators (79120)", "79120"),
    ("Translation / interpretation (74300)", "74300"),
    ("Travel agencies (79110)", "79110"),
    ("TV programme production (59113)", "59113"),
    ("Veterinary (75000)", "75000"),
    ("Video production (59112)", "59112"),
    ("Vocational training (85320)", "85320"),
]

# ─── Full SIC lookup — used for the Category column on every result ───────────
# Covers all codes that might appear on a UK company filing.
SIC_LOOKUP = {
    # Mining & quarrying
    "05100": "Mining of hard coal",
    "06100": "Extraction of crude petroleum",
    "06200": "Extraction of natural gas",
    "07100": "Mining of iron ores",
    "07210": "Mining of uranium ores",
    "07290": "Mining of other non-ferrous metal ores",
    "08110": "Quarrying of ornamental and building stone",
    "08120": "Operation of gravel and sand pits",
    "08910": "Mining of chemical and fertiliser minerals",
    "08920": "Extraction of peat",
    "08930": "Extraction of salt",
    "08990": "Other mining and quarrying NEC",
    "09100": "Support activities for petroleum and natural gas extraction",
    "09900": "Support activities for other mining and quarrying",
    # Food manufacturing
    "10110": "Processing and preserving of meat",
    "10120": "Processing and preserving of poultry meat",
    "10130": "Production of meat and poultry products",
    "10200": "Processing and preserving of fish",
    "10310": "Processing and preserving of potatoes",
    "10320": "Manufacture of fruit and vegetable juice",
    "10390": "Other processing and preserving of fruit and vegetables",
    "10410": "Manufacture of oils and fats",
    "10420": "Manufacture of margarine and similar edible fats",
    "10511": "Liquid milk and cream production",
    "10512": "Butter and cheese production",
    "10519": "Manufacture of other dairy products",
    "10520": "Manufacture of ice cream",
    "10611": "Grain milling",
    "10612": "Manufacture of breakfast cereals and cereal products",
    "10620": "Manufacture of starches and starch products",
    "10710": "Manufacture of bread and fresh pastry goods",
    "10720": "Manufacture of rusks, biscuits and preserved pastry",
    "10730": "Manufacture of pasta, noodles and similar products",
    "10810": "Manufacture of sugar",
    "10821": "Manufacture of cocoa and chocolate",
    "10822": "Manufacture of sugar confectionery",
    "10831": "Tea processing",
    "10832": "Production of coffee",
    "10840": "Manufacture of condiments and seasonings",
    "10850": "Manufacture of prepared meals and dishes",
    "10860": "Manufacture of homogenised food preparations",
    "10890": "Manufacture of other food products NEC",
    "10910": "Manufacture of prepared animal feeds",
    "10920": "Manufacture of prepared pet foods",
    # Beverages
    "11010": "Distilling, rectifying and blending of spirits",
    "11020": "Manufacture of wine from grape",
    "11030": "Manufacture of cider and other fruit wines",
    "11040": "Manufacture of other non-distilled fermented beverages",
    "11050": "Manufacture of beer",
    "11060": "Manufacture of malt",
    "11070": "Manufacture of soft drinks and mineral waters",
    # Tobacco
    "12000": "Manufacture of tobacco products",
    # Textiles
    "13100": "Preparation and spinning of textile fibres",
    "13200": "Weaving of textiles",
    "13300": "Finishing of textiles",
    "13910": "Manufacture of knitted and crocheted fabrics",
    "13921": "Manufacture of soft furnishings",
    "13922": "Manufacture of canvas goods and sacks",
    "13923": "Manufacture of household textiles NEC",
    "13931": "Manufacture of woven or tufted carpets and rugs",
    "13940": "Manufacture of cordage, rope and netting",
    "13950": "Manufacture of non-wovens",
    "13960": "Manufacture of technical and industrial textiles",
    "13990": "Manufacture of other textiles NEC",
    # Apparel
    "14110": "Manufacture of leather clothes",
    "14120": "Manufacture of workwear",
    "14131": "Manufacture of men's outerwear",
    "14132": "Manufacture of women's outerwear",
    "14190": "Manufacture of other wearing apparel",
    "14200": "Manufacture of articles of fur",
    "14310": "Manufacture of knitted and crocheted hosiery",
    "14390": "Manufacture of other knitted articles",
    # Leather
    "15110": "Tanning and dressing of leather",
    "15120": "Manufacture of luggage, handbags and saddlery",
    "15200": "Manufacture of footwear",
    # Wood
    "16100": "Sawmilling and planing of wood",
    "16210": "Manufacture of veneer sheets and wood-based panels",
    "16220": "Manufacture of assembled parquet floors",
    "16230": "Manufacture of builders' carpentry and joinery",
    "16240": "Manufacture of wooden containers",
    "16290": "Manufacture of other wood products",
    # Paper
    "17110": "Manufacture of pulp",
    "17120": "Manufacture of paper and paperboard",
    "17211": "Manufacture of corrugated paper and paperboard",
    "17219": "Manufacture of other containers of paper",
    "17220": "Manufacture of household and sanitary goods from paper",
    "17230": "Manufacture of paper stationery",
    "17240": "Manufacture of wallpaper",
    "17290": "Manufacture of other articles of paper and paperboard NEC",
    # Printing
    "18110": "Printing of newspapers",
    "18121": "Manufacture of printed labels",
    "18129": "Printing NEC",
    "18130": "Pre-press and pre-media services",
    "18140": "Binding and related services",
    "18200": "Reproduction of recorded media",
    # Petroleum
    "19100": "Manufacture of coke oven products",
    "19201": "Mineral oil refining",
    "19209": "Other treatment of petroleum products NEC",
    # Chemicals
    "20110": "Manufacture of industrial gases",
    "20120": "Manufacture of dyes and pigments",
    "20130": "Manufacture of other inorganic basic chemicals",
    "20140": "Manufacture of other organic basic chemicals",
    "20150": "Manufacture of fertilisers and nitrogen compounds",
    "20160": "Manufacture of plastics in primary forms",
    "20170": "Manufacture of synthetic rubber in primary forms",
    "20200": "Manufacture of pesticides and other agrochemical products",
    "20301": "Manufacture of paints and varnishes",
    "20302": "Manufacture of artists' colours",
    "20411": "Manufacture of soap and detergents",
    "20412": "Manufacture of cleaning and polishing preparations",
    "20420": "Manufacture of perfumes and toilet preparations",
    "20510": "Manufacture of explosives",
    "20520": "Manufacture of glues",
    "20530": "Manufacture of essential oils",
    "20590": "Manufacture of other chemical products NEC",
    "20600": "Manufacture of man-made fibres",
    # Pharmaceuticals
    "21100": "Manufacture of basic pharmaceutical products",
    "21200": "Manufacture of pharmaceutical preparations",
    # Rubber & plastics
    "22110": "Manufacture of rubber tyres and tubes",
    "22190": "Manufacture of other rubber products",
    "22210": "Manufacture of plastic plates, sheets, tubes and profiles",
    "22220": "Manufacture of plastic packing goods",
    "22230": "Manufacture of builders' ware of plastic",
    "22290": "Manufacture of other plastic products",
    # Non-metallic minerals
    "23110": "Manufacture of flat glass",
    "23120": "Shaping and processing of flat glass",
    "23130": "Manufacture of hollow glass",
    "23140": "Manufacture of glass fibres",
    "23190": "Manufacture and processing of other glass NEC",
    "23200": "Manufacture of refractory products",
    "23310": "Manufacture of ceramic tiles and flags",
    "23320": "Manufacture of bricks, tiles and construction products in baked clay",
    "23410": "Manufacture of ceramic household and ornamental articles",
    "23490": "Manufacture of other ceramic products",
    "23510": "Manufacture of cement",
    "23520": "Manufacture of lime and plaster",
    "23610": "Manufacture of concrete products for construction",
    "23630": "Manufacture of ready-mixed concrete",
    "23690": "Manufacture of other articles of concrete and plaster",
    "23700": "Cutting, shaping and finishing of stone",
    "23910": "Production of abrasive products",
    "23990": "Manufacture of other non-metallic mineral products NEC",
    # Basic metals
    "24100": "Manufacture of basic iron and steel",
    "24200": "Manufacture of tubes, pipes and hollow profiles",
    "24340": "Cold drawing of wire",
    "24410": "Precious metals production",
    "24420": "Aluminium production",
    "24430": "Lead, zinc and tin production",
    "24440": "Copper production",
    "24450": "Other non-ferrous metal production",
    "24510": "Casting of iron",
    "24520": "Casting of steel",
    "24530": "Casting of light metals",
    # Fabricated metals
    "25110": "Manufacture of metal structures and parts of structures",
    "25120": "Manufacture of doors and windows of metal",
    "25210": "Manufacture of central heating radiators and boilers",
    "25290": "Manufacture of other tanks, reservoirs and containers of metal",
    "25300": "Manufacture of steam generators",
    "25400": "Manufacture of weapons and ammunition",
    "25500": "Forging, pressing, stamping and roll-forming of metal",
    "25610": "Treatment and coating of metals",
    "25620": "Machining",
    "25710": "Manufacture of cutlery",
    "25720": "Manufacture of locks and hinges",
    "25730": "Manufacture of tools",
    "25910": "Manufacture of steel drums and similar containers",
    "25920": "Manufacture of light metal packaging",
    "25930": "Manufacture of wire products, chain and springs",
    "25940": "Manufacture of fasteners and screw machine products",
    "25990": "Manufacture of other fabricated metal products NEC",
    # Electronics
    "26110": "Manufacture of electronic components",
    "26120": "Manufacture of loaded electronic boards",
    "26200": "Manufacture of computers and peripheral equipment",
    "26301": "Manufacture of telegraph and telephone apparatus",
    "26309": "Manufacture of other communication equipment NEC",
    "26400": "Manufacture of consumer electronics",
    "26511": "Manufacture of electronic measuring instruments",
    "26512": "Manufacture of non-electronic measuring instruments",
    "26513": "Manufacture of industrial process control equipment",
    "26520": "Manufacture of watches and clocks",
    "26600": "Manufacture of radiation and electromedical equipment",
    "26701": "Manufacture of optical instruments and photographic equipment",
    "26800": "Manufacture of magnetic and optical media",
    # Electrical equipment
    "27110": "Manufacture of electric motors, generators and transformers",
    "27120": "Manufacture of electricity distribution and control apparatus",
    "27200": "Manufacture of batteries and accumulators",
    "27310": "Manufacture of fibre optic cables",
    "27320": "Manufacture of other electronic and electric wires and cables",
    "27330": "Manufacture of wiring devices",
    "27400": "Manufacture of electric lighting equipment",
    "27510": "Manufacture of electric domestic appliances",
    "27520": "Manufacture of non-electric domestic appliances",
    "27900": "Manufacture of other electrical equipment",
    # Machinery
    "28110": "Manufacture of engines and turbines",
    "28120": "Manufacture of fluid power equipment",
    "28130": "Manufacture of other pumps and compressors",
    "28150": "Manufacture of bearings, gears and driving elements",
    "28210": "Manufacture of ovens, furnaces and furnace burners",
    "28220": "Manufacture of lifting and handling equipment",
    "28230": "Manufacture of office machinery and equipment",
    "28240": "Manufacture of power-driven hand tools",
    "28250": "Manufacture of non-domestic cooling and ventilation equipment",
    "28290": "Manufacture of other general-purpose machinery NEC",
    "28301": "Manufacture of agricultural tractors",
    "28302": "Manufacture of other agricultural and forestry machinery",
    "28410": "Manufacture of metal forming machinery",
    "28490": "Manufacture of other machine tools",
    "28910": "Manufacture of machinery for metallurgy",
    "28920": "Manufacture of machinery for mining, quarrying and construction",
    "28930": "Manufacture of machinery for food, beverage and tobacco processing",
    "28940": "Manufacture of machinery for textile, apparel and leather production",
    "28950": "Manufacture of machinery for paper and paperboard production",
    "28960": "Manufacture of plastics and rubber machinery",
    "28990": "Manufacture of other special-purpose machinery NEC",
    # Vehicles
    "29100": "Manufacture of motor vehicles",
    "29201": "Manufacture of bodies for motor vehicles",
    "29202": "Manufacture of trailers and semi-trailers",
    "29310": "Manufacture of electrical equipment for motor vehicles",
    "29320": "Manufacture of other parts and accessories for motor vehicles",
    # Other transport equipment
    "30110": "Building of ships and floating structures",
    "30120": "Building of pleasure and sporting boats",
    "30200": "Manufacture of railway locomotives and rolling stock",
    "30300": "Manufacture of air and spacecraft",
    "30910": "Manufacture of motorcycles",
    "30920": "Manufacture of bicycles and invalid carriages",
    "30990": "Manufacture of other transport equipment NEC",
    # Furniture & other manufacturing
    "31010": "Manufacture of office and shop furniture",
    "31020": "Manufacture of kitchen furniture",
    "31030": "Manufacture of mattresses",
    "31090": "Manufacture of other furniture",
    "32120": "Manufacture of jewellery and related articles",
    "32130": "Manufacture of imitation jewellery",
    "32200": "Manufacture of musical instruments",
    "32300": "Manufacture of sports goods",
    "32400": "Manufacture of games and toys",
    "32500": "Manufacture of medical and dental instruments",
    "32910": "Manufacture of brooms and brushes",
    "32990": "Other manufacturing NEC",
    # Repair & installation
    "33110": "Repair of fabricated metal products",
    "33120": "Repair of machinery",
    "33130": "Repair of electronic and optical equipment",
    "33140": "Repair of electrical equipment",
    "33150": "Repair and maintenance of ships and boats",
    "33160": "Repair and maintenance of aircraft and spacecraft",
    "33170": "Repair and maintenance of other transport equipment",
    "33190": "Repair of other equipment",
    "33200": "Installation of industrial machinery and equipment",
    # Utilities
    "35110": "Production of electricity",
    "35120": "Transmission of electricity",
    "35130": "Distribution of electricity",
    "35140": "Trade of electricity",
    "35210": "Manufacture of gas",
    "35220": "Distribution of gaseous fuels through mains",
    "35230": "Trade of gas through mains",
    "35300": "Steam and air conditioning supply",
    "36000": "Water collection, treatment and supply",
    "37000": "Sewerage",
    "38110": "Collection of non-hazardous waste",
    "38120": "Collection of hazardous waste",
    "38210": "Treatment and disposal of non-hazardous waste",
    "38220": "Treatment and disposal of hazardous waste",
    "38310": "Dismantling of wrecks",
    "38320": "Recovery of sorted materials",
    "39000": "Remediation activities and other waste management services",
    # Construction
    "41100": "Development of building projects",
    "41201": "Construction of commercial buildings",
    "41202": "Construction of domestic buildings",
    "42110": "Construction of roads and motorways",
    "42120": "Construction of railways and underground railways",
    "42130": "Construction of bridges and tunnels",
    "42210": "Construction of utility projects for fluids",
    "42220": "Construction of utility projects for electricity and telecommunications",
    "42910": "Construction of water projects",
    "42990": "Construction of other civil engineering projects NEC",
    "43110": "Demolition",
    "43120": "Site preparation",
    "43130": "Test drilling and boring",
    "43210": "Electrical installation",
    "43220": "Plumbing, heat and air-conditioning installation",
    "43290": "Other construction installation",
    "43310": "Plastering",
    "43320": "Joinery installation",
    "43330": "Floor and wall covering",
    "43341": "Painting",
    "43342": "Glazing",
    "43390": "Other building completion and finishing",
    "43910": "Roofing activities",
    "43991": "Scaffold erection",
    "43999": "Other specialised construction activities NEC",
    # Motor vehicles trade
    "45111": "Sale of new cars and light motor vehicles",
    "45112": "Sale of used cars and light motor vehicles",
    "45190": "Sale of other motor vehicles",
    "45200": "Maintenance and repair of motor vehicles",
    "45310": "Wholesale trade of motor vehicle parts and accessories",
    "45320": "Retail trade of motor vehicle parts and accessories",
    "45400": "Sale, maintenance and repair of motorcycles",
    # Wholesale
    "46110": "Agents involved in sale of agricultural raw materials",
    "46130": "Agents involved in sale of timber and building materials",
    "46140": "Agents involved in sale of machinery",
    "46150": "Agents involved in sale of furniture and household goods",
    "46160": "Agents involved in sale of textiles",
    "46170": "Agents involved in sale of food and beverages",
    "46180": "Agents specialised in sale of other particular products",
    "46190": "Agents involved in sale of a variety of goods",
    "46210": "Wholesale of grain, seeds and animal feeds",
    "46220": "Wholesale of flowers and plants",
    "46310": "Wholesale of fruit and vegetables",
    "46320": "Wholesale of meat and meat products",
    "46330": "Wholesale of dairy products, eggs and edible oils",
    "46340": "Wholesale of beverages",
    "46350": "Wholesale of tobacco products",
    "46360": "Wholesale of sugar, chocolate and confectionery",
    "46370": "Wholesale of coffee, tea, cocoa and spices",
    "46380": "Wholesale of other food",
    "46390": "Non-specialised wholesale of food, beverages and tobacco",
    "46410": "Wholesale of textiles",
    "46420": "Wholesale of clothing and footwear",
    "46430": "Wholesale of electrical household appliances",
    "46440": "Wholesale of china and glassware",
    "46450": "Wholesale of perfume and cosmetics",
    "46460": "Wholesale of pharmaceutical goods",
    "46470": "Wholesale of furniture, carpets and lighting equipment",
    "46480": "Wholesale of watches and jewellery",
    "46491": "Wholesale of sporting goods",
    "46499": "Wholesale of other household goods",
    "46510": "Wholesale of computers and computer peripheral equipment",
    "46520": "Wholesale of electronic and telecommunications equipment",
    "46610": "Wholesale of agricultural machinery, equipment and supplies",
    "46620": "Wholesale of machine tools",
    "46630": "Wholesale of mining, construction and civil engineering machinery",
    "46640": "Wholesale of machinery for the textile industry",
    "46650": "Wholesale of office furniture",
    "46660": "Wholesale of other office machinery and equipment",
    "46690": "Wholesale of other machinery and equipment",
    "46711": "Wholesale of petroleum and petroleum products",
    "46719": "Wholesale of other fuels and related products",
    "46720": "Wholesale of metals and metal ores",
    "46730": "Wholesale of wood, construction materials and sanitary equipment",
    "46740": "Wholesale of hardware, plumbing and heating equipment",
    "46750": "Wholesale of chemical products",
    "46760": "Wholesale of other intermediate products",
    "46770": "Wholesale of waste and scrap",
    "46900": "Non-specialised wholesale trade",
    # Retail (non-excluded)
    "47190": "Other retail in non-specialised stores",
    "47210": "Retail sale of fruit and vegetables",
    "47220": "Retail sale of meat and meat products",
    "47230": "Retail sale of fish, crustaceans and molluscs",
    "47240": "Retail sale of bread, cakes and flour confectionery",
    "47250": "Retail sale of beverages (off-licences)",
    "47300": "Retail sale of automotive fuel",
    "47410": "Retail sale of computers, peripheral units and software",
    "47421": "Retail sale of mobile telephones",
    "47430": "Retail sale of audio and video equipment",
    "47510": "Retail sale of textiles",
    "47520": "Retail sale of hardware, paints and glass",
    "47530": "Retail sale of carpets, rugs, wall and floor coverings",
    "47540": "Retail sale of electrical household appliances",
    "47591": "Retail sale of musical instruments and scores",
    "47599": "Retail of furniture, lighting and similar NEC",
    "47610": "Retail sale of books",
    "47630": "Retail sale of music and video recordings",
    "47640": "Retail sale of sporting equipment",
    "47650": "Retail sale of games and toys",
    "47710": "Retail sale of clothing",
    "47720": "Retail sale of footwear and leather goods",
    "47730": "Dispensing chemist",
    "47740": "Retail sale of medical and orthopaedic goods",
    "47760": "Retail sale of flowers, plants and seeds",
    "47770": "Retail sale of watches and jewellery",
    "47781": "Retail sale in commercial art galleries",
    "47782": "Retail sale by opticians",
    "47789": "Other retail sale of new goods in specialised stores NEC",
    "47791": "Retail sale of antiques",
    "47910": "Retail sale via mail order or internet",
    "47990": "Other retail sale not in stores, stalls or markets",
    # Transport (non-excluded)
    "49100": "Passenger rail transport",
    "49200": "Freight rail transport",
    "49311": "Urban and suburban passenger transport",
    "49319": "Other urban land passenger transport NEC",
    "49390": "Other passenger land transport (coaches and buses)",
    "49410": "Freight transport by road",
    "49420": "Removal services",
    "49500": "Transport via pipeline",
    "50100": "Sea and coastal passenger water transport",
    "50200": "Sea and coastal freight water transport",
    "50300": "Inland passenger water transport",
    "50400": "Inland freight water transport",
    "51101": "Scheduled passenger air transport",
    "51102": "Non-scheduled passenger air transport",
    "51210": "Freight air transport",
    "52100": "Warehousing and storage",
    "52211": "Operation of motorway service stations",
    "52219": "Other service activities incidental to land transport",
    "52220": "Service activities incidental to water transport",
    "52230": "Service activities incidental to air transport",
    "52241": "Cargo handling for water transport",
    "52242": "Cargo handling for air transport",
    "52243": "Cargo handling for land transport",
    "52290": "Other transportation support activities",
    "53100": "Postal activities under universal service obligation",
    "53201": "Licensed postal operators",
    "53202": "Unlicensed carrier activities",
    # Accommodation
    "55100": "Hotels and similar accommodation",
    "55201": "Holiday centres and villages",
    "55202": "Youth hostels",
    "55209": "Other holiday and short-stay accommodation",
    "55300": "Camping grounds and caravan parks",
    "55900": "Other accommodation",
    # Food service (licensed only — excluded variants handled below)
    "56101": "Licensed restaurants and cafes",
    "56102": "Unlicensed restaurants and cafes",
    "56103": "Takeaway food shops",
    "56210": "Event catering activities",
    "56290": "Other food service activities NEC",
    "56301": "Licensed clubs",
    "56302": "Public houses and bars",
    # Publishing & media
    "58110": "Book publishing",
    "58120": "Publishing of directories and mailing lists",
    "58130": "Publishing of newspapers",
    "58141": "Publishing of consumer and business journals",
    "58190": "Other publishing activities",
    "58210": "Publishing of computer games",
    "58290": "Other software publishing",
    "59111": "Motion picture production activities",
    "59112": "Video production activities",
    "59113": "Television programme production activities",
    "59120": "Motion picture, video and television programme post-production",
    "59130": "Motion picture, video and television programme distribution",
    "59140": "Motion picture projection activities (cinemas)",
    "59200": "Sound recording and music publishing activities",
    "60100": "Radio broadcasting",
    "60200": "Television programming and broadcasting",
    # Telecoms
    "61100": "Wired telecommunications activities",
    "61200": "Wireless telecommunications activities",
    "61300": "Satellite telecommunications activities",
    "61900": "Other telecommunications activities",
    # IT
    "62011": "Ready-made interactive leisure and entertainment software development",
    "62012": "Business and domestic software development",
    "62020": "Information technology consultancy activities",
    "62030": "Computer facilities management activities",
    "62090": "Other information technology service activities",
    # Information services
    "63110": "Data processing, hosting and related activities",
    "63120": "Web portals",
    "63910": "News agency activities",
    "63990": "Other information service activities NEC",
    # Financial (kept in lookup for Category display; excluded from search)
    "64110": "Central banking",
    "64191": "Banks",
    "64192": "Building societies",
    "64202": "Activities of holding companies",
    "64301": "Activities of investment trusts",
    "64999": "Other financial service activities NEC",
    "65110": "Life insurance",
    "65120": "Non-life insurance",
    "65300": "Pension funding",
    "66110": "Administration of financial markets",
    "66120": "Security and commodity contracts dealership",
    "66190": "Mortgage brokers",
    "66210": "Risk and damage evaluation",
    "66220": "Insurance agents and brokers",
    "66290": "Other activities auxiliary to insurance",
    "66300": "Fund management activities",
    # Real estate
    "68100": "Buying and selling of own real estate",
    "68201": "Renting and operating of housing association real estate",
    "68202": "Letting and operating of conference and exhibition facilities",
    "68209": "Other letting and operating of own or leased real estate",
    "68310": "Real estate agencies",
    "68320": "Management of real estate on a fee or contract basis",
    "68330": "Real estate activities on a fee or contract basis",
    # Legal
    "69101": "Barristers at law",
    "69102": "Solicitors",
    "69109": "Activities of other legal services",
    # Accounting
    "69201": "Accounting and auditing activities",
    "69202": "Bookkeeping activities",
    "69203": "Tax consultancy",
    # Head offices & management
    "70100": "Activities of head offices",
    "70210": "Public relations and communications activities",
    "70221": "Financial management consultancy",
    "70229": "Management consultancy activities NEC",
    # Architecture & engineering
    "71111": "Architectural activities",
    "71112": "Urban planning and landscape architectural activities",
    "71121": "Engineering design activities",
    "71122": "Engineering related scientific and technical consulting",
    "71129": "Other engineering activities NEC",
    "71200": "Technical testing and analysis",
    # R&D
    "72110": "Research and experimental development on biotechnology",
    "72190": "Other research and experimental development on natural sciences",
    "72200": "Research and experimental development on social sciences",
    # Advertising & market research
    "73110": "Advertising agencies",
    "73120": "Media representation activities",
    "73200": "Market research and public opinion polling",
    # Other professional
    "74101": "Graphic design activities",
    "74102": "Illustration activities",
    "74201": "Portrait photographic activities",
    "74202": "Other specialist photography",
    "74300": "Translation and interpretation activities",
    "74901": "Patent and copyright activities",
    "74902": "Quantity surveying activities",
    "74909": "Other professional, scientific and technical activities NEC",
    # Veterinary
    "75000": "Veterinary activities",
    # Rental & leasing
    "77110": "Renting and leasing of cars and light motor vehicles",
    "77120": "Renting and leasing of trucks and other heavy vehicles",
    "77210": "Renting and leasing of recreational and sports goods",
    "77290": "Renting and leasing of other personal and household goods",
    "77310": "Renting and leasing of agricultural machinery",
    "77320": "Renting and leasing of construction and civil engineering machinery",
    "77330": "Renting and leasing of office machinery and equipment",
    "77340": "Renting and leasing of water transport equipment",
    "77350": "Renting and leasing of air transport equipment",
    "77390": "Renting and leasing of other machinery and equipment NEC",
    "77400": "Leasing of intellectual property and similar products",
    # Employment
    "78100": "Activities of employment placement agencies",
    "78200": "Temporary employment agency activities",
    "78300": "Human resources provision and management",
    # Travel
    "79110": "Travel agency activities",
    "79120": "Tour operator activities",
    "79900": "Other reservation service and related activities",
    # Security
    "80100": "Private security activities",
    "80200": "Security systems service activities",
    "80300": "Investigation activities",
    # Facilities & admin
    "81100": "Combined facilities support activities",
    "81210": "General cleaning of buildings",
    "81220": "Other building and industrial cleaning",
    "81290": "Other cleaning activities",
    "81300": "Landscape service activities",
    "82110": "Combined office administrative service activities",
    "82190": "Photocopying, document preparation and other specialised office support",
    "82200": "Activities of call centres",
    "82301": "Activities of exhibition and fair organisers",
    "82302": "Activities of conference organisers",
    "82910": "Activities of collection agencies",
    "82920": "Packaging activities",
    "82990": "Other business support service activities NEC",
    # Education (most excluded; vocational in lookup for Category display)
    "85100": "Pre-primary education",
    "85200": "Primary education",
    "85310": "General secondary education",
    "85320": "Technical and vocational secondary education",
    "85410": "Post-secondary non-tertiary education",
    "85421": "First-degree level higher education",
    "85422": "Post-graduate level higher education",
    "85510": "Sports and recreation education",
    "85520": "Cultural education",
    "85530": "Driving school activities",
    "85590": "Other education NEC",
    "85600": "Educational support activities",
    # Health
    "86101": "Hospital activities",
    "86102": "Medical nursing home activities",
    "86210": "General medical practice activities",
    "86220": "Specialist medical practice activities",
    "86230": "Dental practice activities",
    "86290": "Other human health activities",
    "86901": "Physiotherapy and allied health activities",
    "86902": "Other paramedical activities NEC",
    # Residential care
    "87100": "Residential nursing care facilities",
    "87200": "Residential care activities for learning difficulties",
    "87300": "Residential care activities for the elderly and disabled",
    "87900": "Other residential care activities",
    # Social work (excluded; in lookup for Category display)
    "88100": "Social work activities without accommodation for the elderly",
    "88910": "Child day-care activities",
    "88990": "Other social work activities without accommodation NEC",
    # Arts
    "90010": "Performing arts",
    "90020": "Support activities to performing arts",
    "90030": "Artistic creation",
    "90040": "Operation of arts facilities",
    "91010": "Library and archive activities",
    "91020": "Museums activities",
    "91030": "Operation of historical sites and buildings",
    "91040": "Botanical and zoological gardens",
    # Gambling (excluded; in lookup for Category display)
    "92000": "Gambling and betting activities",
    # Sports & recreation
    "93110": "Operation of sports facilities",
    "93120": "Activities of sports clubs",
    "93130": "Fitness facilities",
    "93191": "Activities of racehorse owners",
    "93210": "Activities of amusement parks and theme parks",
    "93290": "Other amusement and recreation activities NEC",
    # Membership organisations (excluded; in lookup for Category display)
    "94110": "Activities of business and employers membership organisations",
    "94120": "Activities of professional membership organisations",
    "94200": "Activities of trade unions",
    "94910": "Activities of religious organisations",
    "94920": "Activities of political organisations",
    "94990": "Activities of other membership organisations NEC",
    # Personal services
    "96010": "Washing and dry-cleaning of textile and fur products",
    "96020": "Hairdressing and other beauty treatment",
    "96030": "Funeral and related activities",
    "96040": "Physical well-being activities",
    "96090": "Other personal service activities NEC",
}

# ─── Exclusion rules ──────────────────────────────────────────────────────────
# These prefixes exclude entire SIC sectors from search and the secondary list.
_EXCLUDED_PREFIXES = (
    "01", "02", "03",   # Agriculture, forestry, fishing
    "64", "65", "66",   # Financial services (priority codes 66190/66220 handled via priority list)
    "84",               # Public administration and defence
    "85",               # Education (vocational training 85320 available via priority list)
    "88",               # Social work and charities
    "92",               # Gambling and betting
    "94",               # Membership organisations (religious, political, charities)
    "99",               # Extraterritorial organisations
)

# Specific codes excluded in addition to the prefix rules above
_EXCLUDED_SPECIFIC = {
    "47110",  # Convenience stores
    "47620",  # Newsagents and stationers
    "47750",  # Retail of cosmetics and beauty products
    "47799",  # Second-hand goods retail
    "47810", "47820", "47890",  # Market stalls (food, textiles, other)
    "49320",  # Taxi operation
    "56102",  # Unlicensed restaurants and cafes
    "56103",  # Takeaway food shops
    "56290",  # Other food service activities (mobile catering, street food)
    "56301",  # Licensed clubs
    "56302",  # Public houses and bars
    "81210", "81220", "81290",  # Cleaning activities
    "90030",  # Individual artistic creation
    "93110",  # Operation of sports facilities (amateur)
    "93120",  # Activities of sports clubs (amateur)
    "96010",  # Laundry and dry-cleaning
    "96020",  # Hairdressing and beauty treatment
    "96090",  # Other personal services (dog walking, nail bars, etc.)
}


def is_excluded_sic(code: str) -> bool:
    """Return True if this SIC code should be excluded from search and the secondary list."""
    s = str(code).strip()
    if any(s.startswith(p) for p in _EXCLUDED_PREFIXES):
        return True
    return s in _EXCLUDED_SPECIFIC


# ─── Derived lists (computed once at import time) ─────────────────────────────
_PRIORITY_CODES = {code for _, code in SIC_OPTIONS}

# Secondary industries: all non-excluded SIC codes not already in the priority list.
# Sorted alphabetically by description for easy browsing.
SECONDARY_SIC_OPTIONS = sorted(
    [(f"{desc} ({code})", code)
     for code, desc in SIC_LOOKUP.items()
     if not is_excluded_sic(code) and code not in _PRIORITY_CODES],
    key=lambda x: x[0].lower()
)

# All SIC codes to loop through when "All industries" is selected.
# Includes priority + secondary (everything non-excluded).
ALL_SEARCH_SICS = list({
    *_PRIORITY_CODES,
    *(code for code in SIC_LOOKUP if not is_excluded_sic(code))
})
